<template><div><h1 id="axios" tabindex="-1"><a class="header-anchor" href="#axios" aria-hidden="true">#</a> Axios</h1>
<p><a href="https://axios-http.com/" target="_blank" rel="noopener noreferrer">Axios<ExternalLinkIcon/></a></p>
<h2 id="请求响应后的数据类型" tabindex="-1"><a class="header-anchor" href="#请求响应后的数据类型" aria-hidden="true">#</a> 请求响应后的数据类型</h2>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="shiki" style="background-color: #282c34"><code><span class="line"><span style="color: #7F848E; font-style: italic">// ./src/service/type.d.ts</span></span>
<span class="line"><span style="color: #C678DD">export</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">interface</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Result</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF">&gt; {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #E06C75">code</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">number</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #E06C75">data</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">T</span></span>
<span class="line"><span style="color: #ABB2BF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="封装axios请求" tabindex="-1"><a class="header-anchor" href="#封装axios请求" aria-hidden="true">#</a> 封装axios请求</h2>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="shiki" style="background-color: #282c34"><code><span class="line"><span style="color: #7F848E; font-style: italic">// ./src/service/index.ts</span></span>
<span class="line"><span style="color: #C678DD">import</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">axios</span><span style="color: #ABB2BF">, { </span><span style="color: #E06C75">AxiosInstance</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">AxiosRequestConfig</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">AxiosResponse</span><span style="color: #ABB2BF"> } </span><span style="color: #C678DD">from</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">&#39;axios&#39;</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 响应数据类型</span></span>
<span class="line"><span style="color: #C678DD">import</span><span style="color: #ABB2BF"> { </span><span style="color: #E06C75">Result</span><span style="color: #ABB2BF"> } </span><span style="color: #C678DD">from</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">&#39;./type&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">class</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Service</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">private</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">instance</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">AxiosInstance</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">private</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">readonly</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">options</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">AxiosRequestConfig</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">private</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">max</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">number</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">private</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">count</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">number</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">private</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">queue</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF">[]</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">constructor</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">options</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">AxiosRequestConfig</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75; font-style: italic">max</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">number</span><span style="color: #ABB2BF">) {</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">instance</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">axios</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">create</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">options</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">options</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">options</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">max</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">max</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">count</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">0</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">queue</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> []</span></span>
<span class="line"></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">//请求拦截器</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">instance</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">interceptors</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">request</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">use</span><span style="color: #ABB2BF">(</span></span>
<span class="line"><span style="color: #ABB2BF">      (</span><span style="color: #E06C75; font-style: italic">options</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">token</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">localStorage</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">getItem</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;token&#39;</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #C678DD">if</span><span style="color: #ABB2BF"> (</span><span style="color: #E06C75">token</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">&amp;&amp;</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">options</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">headers</span><span style="color: #ABB2BF">) {</span></span>
<span class="line"><span style="color: #ABB2BF">          </span><span style="color: #E5C07B">options</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">headers</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">Authorization</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">`Bearer </span><span style="color: #C678DD">${</span><span style="color: #E06C75">token</span><span style="color: #C678DD">}</span><span style="color: #98C379">`</span></span>
<span class="line"><span style="color: #ABB2BF">        }</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">options</span></span>
<span class="line"><span style="color: #ABB2BF">      },</span></span>
<span class="line"><span style="color: #ABB2BF">      (</span><span style="color: #E06C75; font-style: italic">err</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">err</span></span>
<span class="line"><span style="color: #ABB2BF">      }</span></span>
<span class="line"><span style="color: #ABB2BF">    )</span></span>
<span class="line"></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">//响应拦截器</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">instance</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">interceptors</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">response</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">use</span><span style="color: #ABB2BF">(</span></span>
<span class="line"><span style="color: #ABB2BF">      (</span><span style="color: #E06C75; font-style: italic">res</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #7F848E; font-style: italic">//处理mock请求</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #C678DD">if</span><span style="color: #ABB2BF"> (</span><span style="color: #E5C07B">res</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">data</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">code</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">===</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">0</span><span style="color: #ABB2BF">) {</span></span>
<span class="line"><span style="color: #ABB2BF">          </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">res</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">data</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">data</span></span>
<span class="line"><span style="color: #ABB2BF">        }</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">res</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">data</span></span>
<span class="line"><span style="color: #ABB2BF">      },</span></span>
<span class="line"><span style="color: #ABB2BF">      (</span><span style="color: #E06C75; font-style: italic">err</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">err</span></span>
<span class="line"><span style="color: #ABB2BF">      }</span></span>
<span class="line"><span style="color: #ABB2BF">    )</span></span>
<span class="line"><span style="color: #ABB2BF">  }</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">implement</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt;(</span><span style="color: #E06C75; font-style: italic">options</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">AxiosRequestConfig</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75; font-style: italic">resolve</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75; font-style: italic">reject</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF">): </span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// 具体执行函数</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> () </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">instance</span></span>
<span class="line"><span style="color: #ABB2BF">        .</span><span style="color: #61AFEF">request</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF">, </span><span style="color: #E5C07B">AxiosResponse</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">Result</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt;&gt;&gt;(</span><span style="color: #E06C75">options</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">        .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">((</span><span style="color: #E06C75; font-style: italic">res</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">          </span><span style="color: #61AFEF">resolve</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">res</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">as</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">unknown</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">as</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Promise</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt;)</span></span>
<span class="line"><span style="color: #ABB2BF">        })</span></span>
<span class="line"><span style="color: #ABB2BF">        .</span><span style="color: #61AFEF">catch</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">reject</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">        .</span><span style="color: #61AFEF">finally</span><span style="color: #ABB2BF">(() </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">          </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">count</span><span style="color: #56B6C2">--</span></span>
<span class="line"><span style="color: #ABB2BF">          </span><span style="color: #C678DD">if</span><span style="color: #ABB2BF"> (</span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">queue</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">length</span><span style="color: #ABB2BF">) {</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">task</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">queue</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">shift</span><span style="color: #ABB2BF">()</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #61AFEF">task</span><span style="color: #ABB2BF">()</span></span>
<span class="line"><span style="color: #ABB2BF">          }</span></span>
<span class="line"><span style="color: #ABB2BF">        })</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">count</span><span style="color: #56B6C2">++</span></span>
<span class="line"><span style="color: #ABB2BF">    }</span></span>
<span class="line"><span style="color: #ABB2BF">  }</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">request</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt;(</span><span style="color: #E06C75; font-style: italic">options</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">AxiosRequestConfig</span><span style="color: #ABB2BF">): </span><span style="color: #E5C07B">Promise</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt; {</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">new</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Promise</span><span style="color: #ABB2BF">((</span><span style="color: #E06C75; font-style: italic">resolve</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75; font-style: italic">reject</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">task</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">implement</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt;(</span><span style="color: #E06C75">options</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">resolve</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">reject</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #7F848E; font-style: italic">//优化:重复请求</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #C678DD">if</span><span style="color: #ABB2BF"> (</span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">count</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">&gt;=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">max</span><span style="color: #ABB2BF">) {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">queue</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">push</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">task</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">      } </span><span style="color: #C678DD">else</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #61AFEF">task</span><span style="color: #ABB2BF">()</span></span>
<span class="line"><span style="color: #ABB2BF">      }</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"><span style="color: #ABB2BF">  }</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">get</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF">&gt;(</span><span style="color: #E06C75; font-style: italic">options</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">AxiosRequestConfig</span><span style="color: #ABB2BF">): </span><span style="color: #E5C07B">Promise</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt; {</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">request</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt;({ ...</span><span style="color: #E06C75">options</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">method</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;GET&#39;</span><span style="color: #ABB2BF"> })</span></span>
<span class="line"><span style="color: #ABB2BF">  }</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">post</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF">&gt;(</span><span style="color: #E06C75; font-style: italic">options</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">AxiosRequestConfig</span><span style="color: #ABB2BF">): </span><span style="color: #E5C07B">Promise</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt; {</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">request</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt;({ ...</span><span style="color: #E06C75">options</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">method</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;POST&#39;</span><span style="color: #ABB2BF"> })</span></span>
<span class="line"><span style="color: #ABB2BF">  }</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">delete</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF">&gt;(</span><span style="color: #E06C75; font-style: italic">options</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">AxiosRequestConfig</span><span style="color: #ABB2BF">): </span><span style="color: #E5C07B">Promise</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt; {</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">request</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt;({ ...</span><span style="color: #E06C75">options</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">method</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;DELETE&#39;</span><span style="color: #ABB2BF"> })</span></span>
<span class="line"><span style="color: #ABB2BF">  }</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">patch</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF">&gt;(</span><span style="color: #E06C75; font-style: italic">options</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">AxiosRequestConfig</span><span style="color: #ABB2BF">): </span><span style="color: #E5C07B">Promise</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt; {</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">request</span><span style="color: #ABB2BF">&lt;</span><span style="color: #E5C07B">T</span><span style="color: #ABB2BF">&gt;({ ...</span><span style="color: #E06C75">options</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">method</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;PATCH&#39;</span><span style="color: #ABB2BF"> })</span></span>
<span class="line"><span style="color: #ABB2BF">  }</span></span>
<span class="line"><span style="color: #ABB2BF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
