<template><div><h1 id="基础" tabindex="-1"><a class="header-anchor" href="#基础" aria-hidden="true">#</a> 基础</h1>
<h2 id="安装" tabindex="-1"><a class="header-anchor" href="#安装" aria-hidden="true">#</a> 安装</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #282c34"><code><span class="line"><span style="color: #C678DD">import</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">&#39;xgplayer&#39;</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">import</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">FlvJsPlayer</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">from</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">&#39;xgplayer-flv.js&#39;</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">import</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">store</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">from</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">&#39;../store&#39;</span><span style="color: #ABB2BF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">utils</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> {};</span></span>
<span class="line"></span>
<span class="line"><span style="color: #7F848E; font-style: italic">/**</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic"> * 创建 http-flv 直播播放器</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic"> * </span><span style="color: #C678DD; font-style: italic">@param</span><span style="color: #7F848E; font-style: italic"> </span><span style="color: #E5C07B; font-style: italic">{DOM}</span><span style="color: #7F848E; font-style: italic"> </span><span style="color: #E06C75; font-style: italic">parentId</span><span style="color: #7F848E; font-style: italic"> 播放器父级元素 id</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic"> * </span><span style="color: #C678DD; font-style: italic">@param</span><span style="color: #7F848E; font-style: italic"> </span><span style="color: #E5C07B; font-style: italic">{Object}</span><span style="color: #7F848E; font-style: italic"> </span><span style="color: #E06C75; font-style: italic">config</span><span style="color: #7F848E; font-style: italic"> 播放器参数</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic"> */</span></span>
<span class="line"><span style="color: #E5C07B">utils</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">createPlayer</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> (</span><span style="color: #E06C75; font-style: italic">parentId</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75; font-style: italic">config</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #E5C07B">store</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">commit</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;setPlayerCount&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">// 生成监控 DOM 并添加进页面</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">videoDom</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">document</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">createElement</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;div&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">id</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">parentId</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">===</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">&#39;gis-camera-video&#39;</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #C678DD">?</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">`</span><span style="color: #C678DD">${</span><span style="color: #E06C75">parentId</span><span style="color: #C678DD">}</span><span style="color: #98C379">`</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #C678DD">:</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">`</span><span style="color: #C678DD">${</span><span style="color: #E06C75">parentId</span><span style="color: #C678DD">}</span><span style="color: #98C379">-</span><span style="color: #C678DD">${</span><span style="color: #E5C07B">Math</span><span style="color: #ABB2BF">.</span><span style="color: #56B6C2">random</span><span style="color: #ABB2BF">()</span><span style="color: #C678DD">}</span><span style="color: #98C379">`</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #E5C07B">videoDom</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">setAttribute</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;id&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">id</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">parentDom</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">document</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">getElementById</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">parentId</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #E5C07B">parentDom</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">appendChild</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">videoDom</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">urlList</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> [</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// &#39;http://nvr.jiketravel.com/flv/hls/stream_1.flv&#39;,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// &#39;http://nvr1.jiketravel.com/flv/hls/stream_1.flv&#39;,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// &#39;http://nvr2.jiketravel.com/flv/hls/stream_1.flv&#39;</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #98C379">&#39;http://10.0.2.172/live?port=1935&amp;app=myapp&amp;stream=home&#39;</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">  ];</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;config======&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">config</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">// 生成播放器</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">player</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">new</span><span style="color: #ABB2BF"> </span><span style="color: #61AFEF">FlvJsPlayer</span><span style="color: #ABB2BF">({</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">id</span><span style="color: #ABB2BF">: </span><span style="color: #E06C75">id</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">isLive</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// url: &#39;http://live.luopan88.com/live?port=1935&amp;app=myapp&amp;stream=luopan&#39;,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// url: &#39;http://47.100.42.180:8935/live?port=1935&amp;app=myapp&amp;stream=home&#39;,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// url: &#39;http://10.0.2.161/live?port=1935&amp;app=myapp&amp;stream=home&#39;,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// url: urlList[Math.floor(store.state.playerCount / 6)],</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// url: config.url,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">controls</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">false</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">autoplay</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">ignores</span><span style="color: #ABB2BF">: [</span><span style="color: #98C379">&#39;loading&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #98C379">&#39;progress&#39;</span><span style="color: #ABB2BF">],</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">width</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;155px&#39;</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">height</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;109px&#39;</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">/**</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">     * 由于 Chrome 新的 autoplay 政策，必须设置静音才可播放。</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">     * 但经测试 Chrome 下 xgplayer 仍无法自动播放，flv.js 却可播放</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">     * 初步怀疑是 xgplayer 问题</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">     * 其他浏览器暂无此问题（Firefox, Safari, 360极速浏览器, Edge）</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">     */</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">muted</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">flvOptionalConfig</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E06C75">enableWorker</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E06C75">enableStashBuffer</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">false</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E06C75">stashInitialSize</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">128</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    },</span></span>
<span class="line"><span style="color: #ABB2BF">    ...</span><span style="color: #E06C75">config</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">  });</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">// player.once(&#39;complete&#39;, () =&gt; {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//   let htmlMediaElement = document.getElementById(id).childNodes[0];</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//   setInterval(() =&gt; {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//     if (!htmlMediaElement.buffered.length) {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//       return;</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//     }</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//     let end = htmlMediaElement.buffered.end(0);</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//     let diff = end - htmlMediaElement.currentTime;</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//     if (diff &gt;= 1) {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//       htmlMediaElement.currentTime = end;</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//     }</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">//   }, 3000);</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">// });</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #7F848E; font-style: italic">// store.commit(&#39;setPlayerList&#39;, [...store.state.playerList, player]);</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">player</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #ABB2BF">};</span></span>
<span class="line"></span>
<span class="line"><span style="color: #7F848E; font-style: italic">/**</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic"> * 创建一个哈希值</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic"> * </span><span style="color: #C678DD; font-style: italic">@param</span><span style="color: #7F848E; font-style: italic"> </span><span style="color: #E5C07B; font-style: italic">{Number}</span><span style="color: #7F848E; font-style: italic"> </span><span style="color: #E06C75; font-style: italic">hashLength</span><span style="color: #7F848E; font-style: italic"> 哈希值长度，默认24位</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic"> */</span></span>
<span class="line"><span style="color: #E5C07B">utils</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">createHash</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> (</span><span style="color: #E06C75; font-style: italic">hashLength</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Array</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">from</span><span style="color: #ABB2BF">(</span><span style="color: #E5C07B">Array</span><span style="color: #ABB2BF">(</span><span style="color: #E5C07B">Number</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">hashLength</span><span style="color: #ABB2BF">) </span><span style="color: #56B6C2">||</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">24</span><span style="color: #ABB2BF">), () </span><span style="color: #C678DD">=&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">Math</span><span style="color: #ABB2BF">.</span><span style="color: #56B6C2">floor</span><span style="color: #ABB2BF">(</span><span style="color: #E5C07B">Math</span><span style="color: #ABB2BF">.</span><span style="color: #56B6C2">random</span><span style="color: #ABB2BF">() </span><span style="color: #56B6C2">*</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">36</span><span style="color: #ABB2BF">).</span><span style="color: #61AFEF">toString</span><span style="color: #ABB2BF">(</span><span style="color: #D19A66">36</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">  ).</span><span style="color: #61AFEF">join</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">};</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">export</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">default</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">utils</span><span style="color: #ABB2BF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Vue.js 设计的初衷就包括可以被渐进式地采用。这意味着它可以根据需求以多种方式集成到一个项目中。</p>
<p>将 Vue.js 添加到项目中主要有四种方式：</p>
<ol>
<li>在页面上以 <a href="https://v3.cn.vuejs.org/guide/installation.html#cdn" target="_blank" rel="noopener noreferrer">CDN 包<ExternalLinkIcon/></a>的形式导入。</li>
<li>下载 JavaScript 文件并<a href="https://v3.cn.vuejs.org/guide/installation.html#%E4%B8%8B%E8%BD%BD%E5%B9%B6%E8%87%AA%E6%89%98%E7%AE%A1" target="_blank" rel="noopener noreferrer">自行托管<ExternalLinkIcon/></a>。</li>
<li>使用 <a href="https://v3.cn.vuejs.org/guide/installation.html#npm" target="_blank" rel="noopener noreferrer">npm<ExternalLinkIcon/></a> 安装它。</li>
<li>使用官方的 <a href="https://v3.cn.vuejs.org/guide/installation.html#%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7-cli" target="_blank" rel="noopener noreferrer">CLI<ExternalLinkIcon/></a> 来构建一个项目，它为现代前端工作流程提供了功能齐备的构建设置 (例如，热重载、保存时的提示等等)</li>
</ol>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>这是一个提示</p>
</div>
<div class="custom-container warning"><p class="custom-container-title">WARNING</p>
<p>这是一个警告</p>
</div>
<div class="custom-container danger"><p class="custom-container-title">DANGER</p>
<p>这是一个危险警告</p>
</div>
<details class="custom-container details">
<p>这是一个 details 标签</p>
</details>
</div></template>
