<template><div><h1 id="_1、基础语法" tabindex="-1"><a class="header-anchor" href="#_1、基础语法" aria-hidden="true">#</a> 1、基础语法</h1>
<p>Vue 是声明式编程，原生 JavaScript 是命令式编程。</p>
<h2 id="_1-1、cdn-引入" tabindex="-1"><a class="header-anchor" href="#_1-1、cdn-引入" aria-hidden="true">#</a> 1.1、CDN 引入</h2>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="shiki" style="background-color: #282c34"><code><span class="line"><span style="color: #ABB2BF">&lt;</span><span style="color: #E06C75">html</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">lang</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;en&quot;</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">  &lt;</span><span style="color: #E06C75">head</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">meta</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">charset</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;UTF-8&quot;</span><span style="color: #ABB2BF"> /&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">meta</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">http-equiv</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;X-UA-Compatible&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">content</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;IE=edge&quot;</span><span style="color: #ABB2BF"> /&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">meta</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">name</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;viewport&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">content</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;width=device-width, initial-scale=1.0&quot;</span><span style="color: #ABB2BF"> /&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">title</span><span style="color: #ABB2BF">&gt;CDN引入&lt;/</span><span style="color: #E06C75">title</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">  &lt;/</span><span style="color: #E06C75">head</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">  &lt;</span><span style="color: #E06C75">body</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">div</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">id</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;app&quot;</span><span style="color: #ABB2BF">&gt;&lt;/</span><span style="color: #E06C75">div</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">&lt;!-- CDN地址 --&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">script</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">src</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;https://unpkg.com/vue@next&quot;</span><span style="color: #ABB2BF">&gt;&lt;/</span><span style="color: #E06C75">script</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">script</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #7F848E; font-style: italic">// 使用Vue</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">app</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Vue</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">createApp</span><span style="color: #ABB2BF">({</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">template</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">`&lt;h2&gt;Hello World&lt;/h2&gt;&lt;span&gt;你好,前端&lt;/span&gt;`</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">      });</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #7F848E; font-style: italic">// 挂载</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E5C07B">app</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">mount</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;#app&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;/</span><span style="color: #E06C75">script</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">  &lt;/</span><span style="color: #E06C75">body</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">&lt;/</span><span style="color: #E06C75">html</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_1-2、本地引入" tabindex="-1"><a class="header-anchor" href="#_1-2、本地引入" aria-hidden="true">#</a> 1.2、本地引入</h2>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="shiki" style="background-color: #282c34"><code><span class="line"><span style="color: #ABB2BF">&lt;</span><span style="color: #E06C75">html</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">lang</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;en&quot;</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">  &lt;</span><span style="color: #E06C75">head</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">meta</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">charset</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;UTF-8&quot;</span><span style="color: #ABB2BF"> /&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">meta</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">http-equiv</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;X-UA-Compatible&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">content</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;IE=edge&quot;</span><span style="color: #ABB2BF"> /&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">meta</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">name</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;viewport&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">content</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;width=device-width, initial-scale=1.0&quot;</span><span style="color: #ABB2BF"> /&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">title</span><span style="color: #ABB2BF">&gt;本地引入&lt;/</span><span style="color: #E06C75">title</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">  &lt;/</span><span style="color: #E06C75">head</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">  &lt;</span><span style="color: #E06C75">body</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">div</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">id</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;app&quot;</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">      &lt;</span><span style="color: #E06C75">h2</span><span style="color: #ABB2BF">&gt;当前计数: {{counter}}&lt;/</span><span style="color: #E06C75">h2</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">      &lt;</span><span style="color: #E06C75">button</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">@click</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;increment&quot;</span><span style="color: #ABB2BF">&gt;+1&lt;/</span><span style="color: #E06C75">button</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">      &lt;</span><span style="color: #E06C75">button</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">@click</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;decrement&quot;</span><span style="color: #ABB2BF">&gt;-1&lt;/</span><span style="color: #E06C75">button</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;/</span><span style="color: #E06C75">div</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">script</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">src</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;./lib/vue.js&quot;</span><span style="color: #ABB2BF">&gt;&lt;/</span><span style="color: #E06C75">script</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">script</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">app</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Vue</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">createApp</span><span style="color: #ABB2BF">({</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #61AFEF">data</span><span style="color: #ABB2BF">: </span><span style="color: #C678DD">function</span><span style="color: #ABB2BF"> () {</span></span>
<span class="line"><span style="color: #ABB2BF">          </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #E06C75">counter</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">0</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">          };</span></span>
<span class="line"><span style="color: #ABB2BF">        },</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">methods</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">          </span><span style="color: #61AFEF">increment</span><span style="color: #ABB2BF">: </span><span style="color: #C678DD">function</span><span style="color: #ABB2BF"> () {</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">counter</span><span style="color: #56B6C2">++</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #ABB2BF">          },</span></span>
<span class="line"><span style="color: #ABB2BF">          </span><span style="color: #61AFEF">decrement</span><span style="color: #ABB2BF">: </span><span style="color: #C678DD">function</span><span style="color: #ABB2BF"> () {</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">counter</span><span style="color: #56B6C2">--</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #ABB2BF">          },</span></span>
<span class="line"><span style="color: #ABB2BF">        },</span></span>
<span class="line"><span style="color: #ABB2BF">      });</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E5C07B">app</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">mount</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;#app&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;/</span><span style="color: #E06C75">script</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">  &lt;/</span><span style="color: #E06C75">body</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">&lt;/</span><span style="color: #E06C75">html</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_1-3、data-属性" tabindex="-1"><a class="header-anchor" href="#_1-3、data-属性" aria-hidden="true">#</a> 1.3、data 属性</h2>
<p>data 属性是传入一个函数，并且该函数需要返回一个对象。</p>
<p>data 中返回的对象会被 Vue 的响应式系统劫持，之后对该对象的修改或者访问都会在劫持中被处理。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #282c34"><code><span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">obj</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #E06C75">key</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;值&#39;</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">};</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">//方式一(Vue2劫持方法)</span></span>
<span class="line"><span style="color: #E5C07B">Object</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">defineProperty</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">obj</span><span style="color: #ABB2BF">, </span><span style="color: #98C379">&#39;key&#39;</span><span style="color: #ABB2BF">, {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">get</span><span style="color: #ABB2BF">: () </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {},</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">set</span><span style="color: #ABB2BF">: () </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {},</span></span>
<span class="line"><span style="color: #ABB2BF">});</span></span>
<span class="line"></span>
<span class="line"><span style="color: #7F848E; font-style: italic">//方式二(Vue3劫持方法)</span></span>
<span class="line"><span style="color: #C678DD">new</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Proxy</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">obj</span><span style="color: #ABB2BF">, {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">get</span><span style="color: #ABB2BF">: () </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {},</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">set</span><span style="color: #ABB2BF">: () </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {},</span></span>
<span class="line"><span style="color: #ABB2BF">});</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
